version: "2"

volumes:
  # MySQL Data
  com-mysql-data:
    driver: local

services:
  php:
    build: ./devops/docker/php
    volumes:
      - .:/usr/share/nginx/html
  web:
    image: "nginx:1.13.8-alpine"
    volumes:
      - .:/usr/share/nginx/html
      - ./devops/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:80"
    links:
      - "php"

  mysql:
    image: ambientum/mysql:5.7
    container_name: com-mysql
    volumes:
      - com-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=club_of_mind
      - MYSQL_DATABASE=club_of_mind
      - MYSQL_USER=club_of_mind
      - MYSQL_PASSWORD=club_of_mind